queue_rules:
  - name: default
    merge_conditions:
      - "#commits-behind==0"
      - "#approved-reviews-by>=1"
      - "#check-failure==0"
      - check-success=GitGuardian Security Checks

defaults:
  actions:
    queue:
      merge_method:  rebase
      update_method: rebase

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      request_reviews:
        users: [ DaRacci ]
      queue: