# yaml-language-server: $schema=https://docs.mergify.com/mergify-configuration-schema.json

queue_rules:
  - name: duplicated default from merge on approval
    queue_conditions:
      - base=master
      - label~=merge-queue|dependencies
      - "#approved-reviews-by>=1"
      - base=master
      - label~=merge-queue|dependencies
    merge_conditions: []
    merge_method: rebase
    update_method: rebase
  - name: default
    queue_conditions:
      - base=master
      - label~=merge-queue|dependencies
    merge_conditions:
      - "#commits-behind==0"
      - "#approved-reviews-by>=1"
      - "#check-failure==0"
      - check-success=GitGuardian Security Checks
    merge_method: rebase
    update_method: rebase

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      request_reviews:
        users: [DaRacci]
  - name: merge on approval + merge using the merge queue
    conditions: []
    actions:
      queue:
priority_rules:
  - name: priority for queue `duplicated default from merge on approval`
    conditions:
      - "#approved-reviews-by>=1"
    priority: 2250
