queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label~=merge-queue|dependencies
    merge_conditions:
      - "#commits-behind <= 10"
      - "#approved-reviews-by>=1"
      - "#check-failure==0"
    merge_method: rebase
    update_method: rebase
    autoqueue: true
    branch_protection_injection_mode: merge
pull_request_rules:
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position >= 0
    actions:
      label:
        toggle:
          - merge-queued
  - name: merge using the merge queue
    conditions:
      - base=master
      - label~=merge-queue|dependencies
    actions:
      request_reviews:
        users:
          - DaRacci
  - name: merge on approval + merge using the merge queue
    conditions: []
    actions:
      queue:
priority_rules: []
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = master
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = master
    success_conditions:
      - "#commits-behind <= 10"
