keys:
  - &users :
    - &james "age187xlhmks2tcymsnw32jzzxr6lryejma4602e3v0jlrsra5u64pdsxal44a"
  - &hosts :
    - &nixe "age1rm3j9r0fulw4c2l9cfa9tvrznzw2aehgy2xc700lxrxqq00efghsy9wgv7"
    - &surnix "age1hxxjcpvm9cz88xu6d5jv82uavhqg3jjk4e770a0pc2gzak5gs4zsp4798j"
    - &winix "age10f7nnwsce2zj8905m7xelejm37uckp6tn7jk0eteghprjg2uducsgs9yss"
  - &servers :
    - &nixcloud "age1vn626zvqf9hhnwur37fzww0xqts5jp45uuhetk2caggx75wp4umshj235u"
    - &nixdev "age1zeu2cj6mt0nllar0myzhlsgwp0xk2px83vskplu0s2ul87g9634svuhjpw"
    - &nixio "age1azcacxqvwankaf5ma98jk7swwpn6uxmwvdz0azq5fnulrlwk747sr9x2z9"
    - &nixserv "age1hepu4nkwau3p0z2sf40xq0pzzss0wl263m5uey7lfj7usnr7sfeskdkeg4"

creation_rules:
  - path_regex: home/racci/secrets.yaml$
    key_groups:
    - age: [ *james ]

  - path_regex: hosts/desktop/nixe/secrets.yaml$
    key_groups:
    - age: [ *nixe, *james ]

  - path_regex: hosts/laptop/surnix/secrets.yaml$
    key_groups:
    - age: [ *surnix, *james ]

  - path_regex: hosts/desktop/winix/secrets.yaml$
    key_groups:
    - age: [ *winix, *james ]

  - path_regex: hosts/server/nixcloud/secrets.yaml$
    key_groups:
    - age: [ *nixcloud, *james ]

  - path_regex: hosts/server/nixdev/secrets.yaml$
    key_groups:
    - age: [ *nixdev, *james ]

  - path_regex: hosts/server/nixio/secrets.yaml$
    key_groups:
    - age: [ *nixio, *james ]

  - path_regex: hosts/server/nixserv/secrets.yaml$
    key_groups:
    - age: [ *nixserv, *james ]
