# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{ pkgs, lib }:

let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
merge
  (merge
    (merge
      (merge
      {
        "aaron-bond"."better-comments" = vscode-utils.extensionFromVscodeMarketplace {
          name = "better-comments";
          publisher = "aaron-bond";
          version = "3.0.2";
          sha256 = "15w1ixvp6vn9ng6mmcmv9ch0ngx8m85i1yabxdfn6zx3ypq802c5";

        };
        "alefragnani"."project-manager" = vscode-utils.extensionFromVscodeMarketplace {
          name = "project-manager";
          publisher = "alefragnani";
          version = "12.8.0";
          sha256 = "1gp2dd4xm5a4dmaikcng79mfcb8a24mddsdwpgg4bqshcz4q7n5h";

        };
        "bierner"."markdown-preview-github-styles" = vscode-utils.extensionFromVscodeMarketplace {
          name = "markdown-preview-github-styles";
          publisher = "bierner";
          version = "2.1.0";
          sha256 = "1fn9gdf3xj1drch4djn6c9lg94i2r9yjpfrf1a0y4v8q2zjk8sz8";

        };
        "coolbear"."systemd-unit-file" = vscode-utils.extensionFromVscodeMarketplace {
          name = "systemd-unit-file";
          publisher = "coolbear";
          version = "1.0.6";
          sha256 = "0sc0zsdnxi4wfdlmaqwb6k2qc21dgwx6ipvri36x7agk7m8m4736";

        };
        "dustypomerleau"."rust-syntax" = vscode-utils.extensionFromVscodeMarketplace {
          name = "rust-syntax";
          publisher = "dustypomerleau";
          version = "0.6.1";
          sha256 = "0rccp8njr13jzsbr2jl9hqn74w7ji7b2spfd4ml6r2i43hz9gn53";

        };
        "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
          name = "gitlens";
          publisher = "eamodio";
          version = "2025.3.1605";
          sha256 = "1lkdbpw5nknlzamlyfq60bf24bwci8ynadswvb7wn6gbh5wn17xd";

        };
        "editorconfig"."editorconfig" = vscode-utils.extensionFromVscodeMarketplace {
          name = "editorconfig";
          publisher = "editorconfig";
          version = "0.1.0";
          sha256 = "0wwn9prsj1wqbd2r1afjdlysl0qsz44ypbml9a1qfzcy7f6vgkcm";

        };
        "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "prettier-vscode";
          publisher = "esbenp";
          version = "11.0.0";
          sha256 = "1fcz8f4jgnf24kblf8m8nwgzd5pxs2gmrv235cpdgmqz38kf9n54";

        };
        "formulahendry"."code-runner" = vscode-utils.extensionFromVscodeMarketplace {
          name = "code-runner";
          publisher = "formulahendry";
          version = "0.5.0";
          sha256 = "0l9bz3am1la938z9f63km276rrhd9aky10ap9rb71hbq5r87afxw";

        };
        "foxundermoon"."shell-format" = vscode-utils.extensionFromVscodeMarketplace {
          name = "shell-format";
          publisher = "foxundermoon";
          version = "7.2.5";
          sha256 = "0a874423xw7z6zjj7gzzl39jahrrqcf2r16zbcvncw23483m3yli";

        };
        "github"."copilot" = vscode-utils.extensionFromVscodeMarketplace {
          name = "copilot";
          publisher = "github";
          version = "1.4.2628";
          sha256 = "1i5sklmnykbxdr9mzrjk07s5gln5fdbrd1xr8pc8fh4k625z3hry";

        };
        "github"."copilot-chat" = vscode-utils.extensionFromVscodeMarketplace {
          name = "copilot-chat";
          publisher = "github";
          version = "0.0.1";
          sha256 = "0afsy1nvcd7n9idd1xpicyp5k68bs5vfd40v2fls3sz1hmd641sz";

        };
        "github"."vscode-github-actions" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-github-actions";
          publisher = "github";
          version = "0.24.4";
          sha256 = "0371rms5cq2s7kfbzx078bfp7lcyq3lnxp1hrw1wy5igz94lvicp";

        };
        "github"."vscode-pull-request-github" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-pull-request-github";
          publisher = "github";
          version = "0.1.1";
          sha256 = "09acn5axpxvfaxicj0jwz714mc698cw5q89qms87rvldiaa8iw1n";

        };
        "gruntfuggly"."todo-tree" = vscode-utils.extensionFromVscodeMarketplace {
          name = "todo-tree";
          publisher = "gruntfuggly";
          version = "0.0.217";
          sha256 = "1d0vq2p7aqfrq1jxqici01dw0wy88rb12qwvvhi3mccy1gayq77c";

        };
        "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
          name = "nix-ide";
          publisher = "jnoortheen";
          version = "0.4.16";
          sha256 = "0mhc58lzdn153yskqi6crvzx6pgi1d72mdhmnpc4qkbf1wx47l9i";

        };
        "jscearcy"."rust-doc-viewer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "rust-doc-viewer";
          publisher = "jscearcy";
          version = "1.0.0";
          sha256 = "1ag04d5djcmr4gwzhfnf2ygzldvpmk2rhrb2xywbjqs9vpf5jz61";

        };
        "matthewpi"."caddyfile-support" = vscode-utils.extensionFromVscodeMarketplace {
          name = "caddyfile-support";
          publisher = "matthewpi";
          version = "0.4.0";
          sha256 = "1fjhirybvb92frqj1ssh49a73q497ny69z9drdjlkpaccpbvb0r7";

        };
        "mkhl"."direnv" = vscode-utils.extensionFromVscodeMarketplace {
          name = "direnv";
          publisher = "mkhl";
          version = "0.17.0";
          sha256 = "1n2qdd1rspy6ar03yw7g7zy3yjg9j1xb5xa4v2q12b0y6dymrhgn";

        };
        "ms-azuretools"."vscode-docker" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-docker";
          publisher = "ms-azuretools";
          version = "0.6.2";
          sha256 = "1is5b7l6if103219d2bg4gar02p0asq87qswnkzgjqpnawrgkshd";

        };
        "ms-python"."black-formatter" = vscode-utils.extensionFromVscodeMarketplace {
          name = "black-formatter";
          publisher = "ms-python";
          version = "2025.2.0";
          sha256 = "0kiz9rv62sg6kj6h3csmxr1jzv6falcgylspq7ayjainkrr73yqh";

        };
        "ms-python"."gather" = vscode-utils.extensionFromVscodeMarketplace {
          name = "gather";
          publisher = "ms-python";
          version = "2022.3.2";
          sha256 = "0624b0bxk5q3y9pnggqpfgf7rj6363nbzcrzv3p0pzswrxyi443i";

        };
        "ms-python"."isort" = vscode-utils.extensionFromVscodeMarketplace {
          name = "isort";
          publisher = "ms-python";
          version = "2023.13.13171013";
          sha256 = "1dsw2kb8klq84f2gn7v6fhj2w80idx1glcnszasgwmngfa5ps5ah";

        };
        "ms-python"."mypy-type-checker" = vscode-utils.extensionFromVscodeMarketplace {
          name = "mypy-type-checker";
          publisher = "ms-python";
          version = "2025.3.10801012";
          sha256 = "1bfzyvyq213k3lsi3jp50h91dcgfa7l4ijzynvqyg4zi0dhkbsyi";

        };
        "ms-python"."pylint" = vscode-utils.extensionFromVscodeMarketplace {
          name = "pylint";
          publisher = "ms-python";
          version = "2025.2.0";
          sha256 = "0s3lj4kgblprxkl9qcdiy2brwmaq1l7v1camvb9rpd50xgz9h6nx";

        };
        "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-pylance";
          publisher = "ms-python";
          version = "2025.3.103";
          sha256 = "0frsl428ggnivlabw7y5w9hxa453ix9c2rx47r1yciq3gscw1alm";

        };
        "ms-vscode"."powershell" = vscode-utils.extensionFromVscodeMarketplace {
          name = "powershell";
          publisher = "ms-vscode";
          version = "0.0.1";
          sha256 = "0p4dcp2lnc9aqhn3j7dc7n4dhv8hav4jpx45nmykrv9shh2ja40h";

        };
        "ms-vscode-remote"."remote-ssh" = vscode-utils.extensionFromVscodeMarketplace {
          name = "remote-ssh";
          publisher = "ms-vscode-remote";
          version = "0.119.2025031815";
          sha256 = "0ma5rvbh02vi1162117g7s7ljgajn1p55zlcbdvk462p3iyqq77j";

        };
        "pkief"."material-icon-theme" = vscode-utils.extensionFromVscodeMarketplace {
          name = "material-icon-theme";
          publisher = "pkief";
          version = "1.0.0";
          sha256 = "10m3wa4n320dv0m308nmbmpa8mh4yha2sy9mzwsr4awgvhqaqgl0";

        };
        "rogalmic"."bash-debug" = vscode-utils.extensionFromVscodeMarketplace {
          name = "bash-debug";
          publisher = "rogalmic";
          version = "0.3.9";
          sha256 = "0n7lyl8gxrpc26scffbrfczdj0n9bcil9z83m4kzmz7k5dj59hbz";

        };
        "ruschaaf"."extended-embedded-languages" = vscode-utils.extensionFromVscodeMarketplace {
          name = "extended-embedded-languages";
          publisher = "ruschaaf";
          version = "1.3.0";
          sha256 = "17y48hslb2lm187qkr3qxhh5793canrj5yb5mr40y6hz6jg6cq60";

        };
        "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
          name = "even-better-toml";
          publisher = "tamasfe";
          version = "0.21.2";
          sha256 = "0208cms054yj2l8pz9jrv3ydydmb47wr4i0sw8qywpi8yimddf11";

        };
        "wayou"."vscode-todo-highlight" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-todo-highlight";
          publisher = "wayou";
          version = "1.0.5";
          sha256 = "1sg4zbr1jgj9adsj3rik5flcn6cbr4k2pzxi446rfzbzvcqns189";

        };
        "zhuangtongfa"."material-theme" = vscode-utils.extensionFromVscodeMarketplace {
          name = "material-theme";
          publisher = "zhuangtongfa";
          version = "0.0.1";
          sha256 = "18fls9bhgzxlq9zggcim05nxp74mwkc46rsr9zyd1m2s7v1vj6rb";

        };
      }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) {
          "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
            name = "terraform";
            publisher = "hashicorp";
            version = "1.4.0";
            sha256 = "0b3cqxaay85ab10x1cg7622rryf4di4d35zq9nqcjg584k6jjb34";
            arch = "linux-x64";

          };
          "ms-python"."debugpy" = vscode-utils.extensionFromVscodeMarketplace {
            name = "debugpy";
            publisher = "ms-python";
            version = "2023.3.12921008";
            sha256 = "031wqyckf7bnfmfjphw662ihy3rxyngzw05vfk0w2jhbxlahgk8b";
            arch = "linux-x64";

          };
          "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-xml";
            publisher = "redhat";
            version = "0.21.0";
            sha256 = "0a5vqxcp5nwhnksj8m3yy748zdkvgsjjax833527imxs86dq6m1x";
            arch = "linux-x64";

          };
          "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
            name = "rust-analyzer";
            publisher = "rust-lang";
            version = "0.3.1051";
            sha256 = "1czw0hlv6h3rmw6dvgyqvsra07qff4mi3wnjqw8k2g9kdysp2jkj";
            arch = "linux-x64";

          };
        }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) {
        "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
          name = "terraform";
          publisher = "hashicorp";
          version = "1.4.0";
          sha256 = "0b3cqxaay85ab10x1cg7622rryf4di4d35zq9nqcjg584k6jjb34";
          arch = "linux-arm64";

        };
        "ms-python"."debugpy" = vscode-utils.extensionFromVscodeMarketplace {
          name = "debugpy";
          publisher = "ms-python";
          version = "2023.3.12921008";
          sha256 = "1dnzl6rw5cq98p19wqxfl8j82x9z1ghjmw9q962niv1pd03jiqji";
          arch = "linux-arm64";

        };
        "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-xml";
          publisher = "redhat";
          version = "0.21.0";
          sha256 = "1jdfyivjjihablvphskmr919rjdb9akd2ynffwhjl2wrfjxb8rwb";
          arch = "linux-arm64";

        };
        "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "rust-analyzer";
          publisher = "rust-lang";
          version = "0.3.1051";
          sha256 = "1czw0hlv6h3rmw6dvgyqvsra07qff4mi3wnjqw8k2g9kdysp2jkj";
          arch = "linux-arm64";

        };
      }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) {
      "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
        name = "terraform";
        publisher = "hashicorp";
        version = "1.4.0";
        sha256 = "0b3cqxaay85ab10x1cg7622rryf4di4d35zq9nqcjg584k6jjb34";
        arch = "darwin-x64";

      };
      "ms-python"."debugpy" = vscode-utils.extensionFromVscodeMarketplace {
        name = "debugpy";
        publisher = "ms-python";
        version = "2023.3.12921009";
        sha256 = "1ffla764r1sxisxkl3swa4s9bg3rj8076f4jygbxxs1lcbdbly1x";
        arch = "darwin-x64";

      };
      "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
        name = "vscode-xml";
        publisher = "redhat";
        version = "0.21.0";
        sha256 = "0369ypsgpp605gspp4x88zkhw3jlg36j95i55nxrsgf2ar3na4qh";
        arch = "darwin-x64";

      };
      "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
        name = "rust-analyzer";
        publisher = "rust-lang";
        version = "0.3.1051";
        sha256 = "1czw0hlv6h3rmw6dvgyqvsra07qff4mi3wnjqw8k2g9kdysp2jkj";
        arch = "darwin-x64";

      };
    }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) {
    "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
      name = "terraform";
      publisher = "hashicorp";
      version = "1.4.0";
      sha256 = "0b3cqxaay85ab10x1cg7622rryf4di4d35zq9nqcjg584k6jjb34";
      arch = "darwin-arm64";

    };
    "ms-python"."debugpy" = vscode-utils.extensionFromVscodeMarketplace {
      name = "debugpy";
      publisher = "ms-python";
      version = "2023.3.12921008";
      sha256 = "16qm475f6sf4bb3vs1g9iy5hnxspinv12n1f5ssqgnmpk6nszb5l";
      arch = "darwin-arm64";

    };
    "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
      name = "vscode-xml";
      publisher = "redhat";
      version = "0.21.0";
      sha256 = "1lszr7w55vryxdww6c29namh4d8cqgk85kj1h663wshzp97l2ci3";
      arch = "darwin-arm64";

    };
    "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
      name = "rust-analyzer";
      publisher = "rust-lang";
      version = "0.3.1051";
      sha256 = "1czw0hlv6h3rmw6dvgyqvsra07qff4mi3wnjqw8k2g9kdysp2jkj";
      arch = "darwin-arm64";

    };
  })
