name: "Setup Nix with Lix & Caches"
description: "Setup Nix with Lix & Caches"

inputs:
  arch:
    description: "What architecture to install for"
    required: true
  TS_OAUTH_CLIENT_ID:
    description: "Tailscale OAuth Client ID"
    required: true
  TS_OAUTH_SECRET:
    description: "Tailscale OAuth Secret"
    required: true
  ATTIC_ENDPOINT:
    description: "Attic endpoint"
    required: true
  ATTIC_CACHE:
    description: "Attic cache"
    required: true
  ATTIC_TOKEN:
    description: "Attic token"
    required: true

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        source-url: "${{ format('https://install.lix.systems/lix/lix-installer-{0}', inputs.arch) }}"

    # Setup TS so we can access the cache
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ inputs.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ inputs.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Setup Attic cache
      uses: ryanccn/attic-action@v0
      with:
        endpoint: ${{ inputs.ATTIC_ENDPOINT }}
        cache: ${{ inputs.ATTIC_CACHE }}
        token: ${{ inputs.ATTIC_TOKEN }}
