name: "Setup Nix with Lix & Caches"
description: "Setup Nix with Lix & Caches"

inputs:
  arch:
    description: "What architecture to install for"
    required: true
    default: "x86_64-linux"
  TS_OAUTH_CLIENT_ID:
    description: "Tailscale OAuth Client ID"
    required: false
  TS_OAUTH_SECRET:
    description: "Tailscale OAuth Secret"
    required: false
  ATTIC_ENDPOINT:
    description: "Attic endpoint"
    required: false
  ATTIC_CACHE:
    description: "Attic cache"
    required: false
  ATTIC_TOKEN:
    description: "Attic token"
    required: false

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        source-url: "${{ format('https://install.lix.systems/lix/lix-installer-{0}', inputs.arch) }}"
        extra-conf: |
          accept-flake-config = true
          experimental-features = nix-command flakes pipe-operator
          trusted-substituters = https://cache.nixos.org https://cache.racci.dev/global https://nix-community.cachix.org https://nix-community.cachix.org/ https://chaotic-nyx.cachix.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= global:OKNSxDYKp8Q8Tr5/5Bc7CYVSfvdFQV0dMhpG0fOAG0k= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= chaotic-nyx.cachix.org-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8=

    # Setup TS so we can access the cache
    - name: Tailscale
      uses: tailscale/github-action@v3
      if: ${{ !env.ACT && inputs.TS_OAUTH_CLIENT_ID && inputs.TS_OAUTH_SECRET }}
      with:
        oauth-client-id: ${{ inputs.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ inputs.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Setup Attic cache
      uses: ryanccn/attic-action@v0
      if: ${{ !env.ACT && inputs.ATTIC_ENDPOINT && inputs.ATTIC_CACHE && inputs.ATTIC_TOKEN }}
      with:
        endpoint: ${{ inputs.ATTIC_ENDPOINT }}
        cache: ${{ inputs.ATTIC_CACHE }}
        token: ${{ inputs.ATTIC_TOKEN }}
