labels:
  platform: linux/amd64

when:
  - event: manual
  - event: [push, pull_request]
    branch: master

steps:
  - name: Run flake checks
    image: registry.racci.dev/lix-woodpecker:latest
    pull: true
    commands: |
      nix run .#archive-flakes -- "." "flake/ci" "flake/dev"
      nix run nixpkgs#nix-fast-build -- --skip-cached --no-nom
