# Pipeline to build and publish the lix-woodpecker image when nixpkgs or lix inputs change,
# or when the lix-woodpecker package definition changes.
#
# This pipeline runs on pushes to master that modify `flake.lock` or `pkgs/lix-woodpecker/`.
# It compares the locked revisions for the `nixpkgs` and `lix` inputs, and checks for changes
# to the package definition, before deciding whether to publish the image.

when:
  - event: push
    branch: master
    path: [flake.lock, pkgs/lix-woodpecker/**]

steps:
  - name: Check for input changes
    image: registry.racci.dev/lix-woodpecker:latest
    commands: |
      # Check if pkgs/lix-woodpecker changed
      if [ -n "${CI_PREV_COMMIT_SHA:-}" ]; then
        if git diff --quiet "${CI_PREV_COMMIT_SHA}" HEAD -- pkgs/lix-woodpecker/; then
          echo "No changes to pkgs/lix-woodpecker/."
        else
          echo "Detected changes to pkgs/lix-woodpecker/; will publish."
          echo "SHOULD_PUBLISH=true" >> envvar
          exit 0
        fi
      else
        echo "CI_PREV_COMMIT_SHA not set; assuming changes occurred."
        echo "SHOULD_PUBLISH=true" >> envvar
        exit 0
      fi

      get_locked_rev() {
        local lock_file="$1"
        local input_name="$2"
        local node
        node=$(jq -r --arg input "$input_name" '.nodes.root.inputs[$input] // ""' "$lock_file")
        if [ -z "$node" ]; then
          printf ''
          return
        fi
        jq -r --arg node "$node" '.nodes[$node].locked.rev // ""' "$lock_file"
      }

      current_nixpkgs_rev=$(get_locked_rev flake.lock nixpkgs)
      current_lix_rev=$(get_locked_rev flake.lock lix)

      prev_lock_path=$(mktemp)
      trap 'rm -f "$prev_lock_path"' EXIT

      if ! git show "${CI_PREV_COMMIT_SHA}:flake.lock" > "$prev_lock_path" 2>/dev/null; then
        echo "Previous flake.lock not available; assuming inputs changed."
        echo "SHOULD_PUBLISH=true" >> envvar
        exit 0
      fi

      previous_nixpkgs_rev=$(get_locked_rev "$prev_lock_path" nixpkgs || true)
      previous_lix_rev=$(get_locked_rev "$prev_lock_path" lix || true)

      if [ -n "$previous_nixpkgs_rev" ] && [ -n "$previous_lix_rev" ] && \
          [ "$current_nixpkgs_rev" = "$previous_nixpkgs_rev" ] && \
          [ "$current_lix_rev" = "$previous_lix_rev" ]; then
        echo "nixpkgs and lix inputs unchanged; skipping publish."
        echo "SHOULD_PUBLISH=false" >> envvar
      else
        echo "Detected changes to nixpkgs or lix inputs; will publish."
        echo "SHOULD_PUBLISH=true" >> envvar
      fi

  - name: Publish to Registry
    image: registry.racci.dev/lix-woodpecker:latest
    when:
      evaluate: 'BUILD_PUBLISH == "true"'
    environment:
      REGISTRY_USER:
        from_secret: REGISTRY_USER
      REGISTRY_TOKEN:
        from_secret: REGISTRY_TOKEN
    commands: nix run ".#lix-woodpecker.copyToRegistry" -- --dest-creds "$REGISTRY_USER:$REGISTRY_TOKEN"
