# Pipeline to update all flake.lock files and create a single PR with all changes.
# Required secrets:
#   - GITHUB_TOKEN: Fine-grained PAT with `contents:write` and `pull-requests:write` scopes
#   - GPG_PRIVATE_KEY: GPG private key for signing commits (optional)
#   - GPG_FINGERPRINT: GPG key fingerprint (optional)
#   - GPG_PASSPHRASE: GPG key passphrase (optional)
#
# Trigger this pipeline via cron job or manually from the Woodpecker UI.
# You must create a cron job named "update-flake-inputs" in the Woodpecker UI.

when:
  - event: manual
  - event: cron
    cron: update-flake-inputs

steps:
  - name: Update all flake.lock files
    image: registry.racci.dev/lix-woodpecker:latest
    pull: true
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GPG_PRIVATE_KEY:
        from_secret: GPG_PRIVATE_KEY
      GPG_FINGERPRINT:
        from_secret: GPG_FINGERPRINT
      GPG_PASSPHRASE:
        from_secret: GPG_PASSPHRASE
    commands: |
      nix run .#setup-git

      export NIX_CONFIG="access-tokens = github.com=$${GITHUB_TOKEN}"
      nix run .#update-locks -- \
        --flake-dirs ["." "flake/ci" "flake/dev" "flake/nixos" "flake/home-manager"] \
        --commit-message "chore(deps): Update <flake>"

      # Check if we have commits ahead of origin
      COMMITS_AHEAD=$(git rev-list --count origin/master..HEAD 2>/dev/null || echo "0")
      if [ "$COMMITS_AHEAD" -eq 0 ]; then
        echo "No new commits to push."
        exit 0
      fi

      nix run .#create-pr -- \
        --title "chore(deps): Update flake inputs" \
        --body "This PR updates the flake inputs to their latest versions, see individual commits for changes." \
        --branch "update/flake-inputs-all" \
        --base "master"
