name: Update VSCode Extensions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * */3"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-nix
        with:
          arch: x86_64-linux
          TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
          ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

      - name: Run nix4vscode
        run: nix develop --no-pure-eval --accept-flake-config --command "update-vscode"

      - name: Build Extensions
        run: ./utils/build-vscode-extensions.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): Update VSCode extensions"
          branch: update-vscode-extensions
          title: "chore(deps): Update VSCode extensions"
          labels: "dependencies, automated"
