name: Update VSCode Extensions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * */3"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          arch: x86_64-linux
          TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
          ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

      - name: Run nix4vscode
        run: |
          DIR="modules/home-manager/purpose/development/editors/vscode"
          CONFIG="$DIR/config.toml"
          NIX_FILE="$DIR/extensions.nix"
          VSCODE_VERSION=$(nix eval --raw nixpkgs#vscode.version)

          sed -i "s/vscode_version = \".*\"/vscode_version = \"$VSCODE_VERSION\"/" "$CONFIG"
          nix run github:nix-community/nix4vscode -- "$CONFIG" -o "$NIX_FILE"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(deps): Update VSCode extensions"
